apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    # example
    cat:
      message: にゃ～
      colour: blue

    # rest api
    api:
      ip: 127.0.0.1
      port: 3000
