apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.ports.service }}
    targetPort: {{ .Values.ports.docker }}
  selector:
    app: {{ .Release.Name }}
