# example
# these fields can be set with the env vars NEKO_CAT_MESSAGE and NEKO_CAT_COLOUR
# env var values override those set in the config file
cat:
  message: にゃ～
  colour: blue

# rest api
api:
  ip: 127.0.0.1
  port: 3000

# mongodb databsae
mongo:
  dbstr: NEKO_MONGO_DBSTR
