name: Build Docker image

on:
  workflow_call:
  push:
    branches:
      - master

env:
  REGISTRY_NAME: ghcr.io
  REGISTRY_USER: ${{ github.repository_owner }}
  REGISTRY_PASS: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yaml
  build:
    name: Docker
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Docker metadata
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=latest
      - name: Setup qemu
        uses: docker/setup-qemu-action@v1
      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASS }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
