name: Deploy to Kubernetes

on:
  workflow_call:
  push:
    branches:
      - master

env:
  KUBE_CLUSTER: k8s-bandsy
  HELM_RELEASE: ${{ github.event.repository.name }}
  HELM_NAMESPACE: anime-notifier
  HELM_CHART: ./chart

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yaml
  build:
    name: Build
    needs: check
    uses: ./.github/workflows/build.yaml
  deploy:
    name: Kubernetes
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - name: Setup doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save kubeconfig
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.KUBE_CLUSTER }}
      - name: Update deployment
        run: |
          helm upgrade \
            ${{ env.HELM_RELEASE }} \
            ${{ env.HELM_CHART }} \
            --namespace ${{ env.HELM_NAMESPACE }} \
            --install \
            --atomic \
            --set-string mongo.dbstr='${{ secrets.MONGO_DBSTR }}' \
            --set-string mongo.ca='${{ secrets.MONGO_CA }}'
